### PR TITLE
Feature/tr translation

### PR DESCRIPTION
**Pull request by ilhan-mstf**
# GitHub Resume Generator

GitHub Flow PR Image

Thank you so much for opening a pull request! :smiley:

Please provide the following information where possible to help the pull request reviewer merge your PR quicker!

## Relevant Project Issue Numbers :hash:

_Add any related issue numbers from the GitHub project. Append the `#` symbol before issue numbers._

> #15 

## Involved Project Members :bust_in_silhouette:

_Tag any GitHub usernames involved or directly responsible for reviewing the proposed changes. Append the `@` symbol before usernames._

> @sabesansathananthan 

## An Explanation of Your Changes :speech_balloon:

Aded Turkish translation

## For transilators.

- [ ] Create a file called `README.lang.md` in the translations folder.
  lang means shorten form of your language Refer this [site](https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code).

- [x] Check all the links are working.

- [x] Check all the parts are translated.
- [x] If about and built-with are not working then inspect the page and copy the href and paste in your file.
- [x] Edit the translations/Translations.md adding you language icon/link
- [x] Edit the main README.md adding your language icon

### CODE REVIEW

**Comment by sabesansathananthan** [comment]
Thank you For your PR...

**Comment by sabesansathananthan** [comment]
@esau-morais  could you please review it ..

**Review by sabesansathananthan — APPROVED** [review]
Thank you <3

**Review by esau-morais — APPROVED** [review]
Thank you for contribute with Turkish language!!

_Note: It looks all  good and following the template_

**Pull request merged**
