### PR TITLE
Add Telugu Language

### PR DESCRIPTION
**Pull request by Narasimhag**

### CODE REVIEW

**Review by esau-morais — CHANGES_REQUESTED** [review]
Thank you for contribute with Telugu language!

_Note: You need to follow all these required steps:_

- [ ] Change the main `README.md` adding the language icon

_Note: To get the right icon, use [this template](https://github.com/sabesansathananthan/React-GitHub-Resume/issues/15#issuecomment-704188333)_

**Review by esau-morais — APPROVED** [review]
Thank you for contribute for Telugu language!!

_Note: Now, it looks all good_

**Comment by Narasimhag** [comment]
It is my pleasure!

**Review by sabesansathananthan — CHANGES_REQUESTED** [review]
Take a pull from upstream and resolve conflicts

**Comment by Narasimhag** [comment]
Done, merge conflicts fixed.

**Review by sabesansathananthan — APPROVED** [review]
Thank you for your PR

**Pull request merged**
