### PR TITLE
Add Dark Mode

### PR DESCRIPTION
**Pull request by mayank**
For #13 

Added using `darkmode.js`. Screenshots attached.

Screenshot 2020-10-06 at 5 03 53 PM

Screenshot 2020-10-06 at 5 03 28 PM

### CODE REVIEW

**Comment by sabesansathananthan** [comment]
@mayank 
The dark mode shows negative images. Could you please fix it?
Capture1
Capture

**Comment by mayank** [comment]
It's a bit odd. @sabesansathananthan what can you share your OS and Browser?

**Comment by sabesansathananthan** [comment]
Brave browser. Is it depend on the browser?

**Comment by mayank** [comment]
Yes, maybe some CSS is inverting the images as well. Can you check now, I have removed the inversion from image.

**Comment by sabesansathananthan** [comment]
Our current system has a blue background and a white container for a spinner, resume, and Search form.  like below:

Capture
Capture1

but this is your implementation. I vanish the blue background and full plane white. 

Capture2
Capture3


Could you please make the light blue background in dark blue (#072540)  background in the night mode?  in the light mode light blue background is also not there

**Comment by mayank** [comment]
@sabesansathananthan I have fixed the background problem. 
I would recommend keeping the background as close to black as possible. Because dark mode is mainly to create a focus on text and reduce the battery drainage on OLED panels which only works in case of black color.

**Comment by sabesansathananthan** [comment]
but we need to different the background and the container. otherwise, implementation is no use. and language color codes are according to the GitHub linguist. Don't change it in dark mode. but I watched some websites they also use dark blue as well. So could you fix it

Capture
Capture2

**Comment by sabesansathananthan** [comment]
@mayank  could you please fulfill the suggestions.

**Comment by esau-morais** [comment]
@mayank , please, resolve the conflicts and give a feedback about how is going the process to add dark mode

_Note: If it takes more than one week, we must close this issue and PR_

**Comment by mayank** [comment]
@esau-morais @sabesansathananthan working on it!

**Comment by mayank** [comment]
@sabesansathananthan check and confirm. Changes are done!

**Comment by sabesansathananthan** [comment]
@mayank brother, I expect the site like hacktoberfest offl page... Color codes are not good.. 
refer this site https://hacktoberfest.digitalocean.com/

**Comment by mayank** [comment]
> 072540
@sabesansathananthan I have implemented the color you mentioned here.

**Comment by mayank** [comment]
> @mayank Our current system has a blue background and a white container for a spinner, resume, and Search form. like below:
> 
> Capture
> Capture1
> 
> but this is your implementation. I vanish the blue background and full plane white.
> 
> Capture2
> Capture3
> 
> Could you please make the light blue background in dark blue (#072540) background in the night mode? in the light mode light blue background is also not there

@sabesansathananthan I have implemented the color you mentioned here.

**Comment by mayank** [comment]
@sabesansathananthan anyways I am closing this.

**Comment by sabesansathananthan** [comment]
Thank you ❤❤❤

**Pull request closed without merging**
