### PR TITLE
add :: language dropdown and header section

### PR DESCRIPTION
**Pull request by erdemuslu**

### CODE REVIEW

**Review by sabesansathananthan — COMMENTED** [review]
Add i18next with this PR

**Comment by erdemuslu** [comment]
I added i18next. Can you check and merge it? Thanks.

**Comment by erdemuslu** [comment]
Hi again @sabesansathananthan, could you check?

**Comment by sabesansathananthan** [comment]
please do the following steps change the language to french ---> search your profile --> click back button in the resume..

your drop-down shows English and content shows in french
Capture

**Comment by erdemuslu** [comment]
@sabesansathananthan I fixed it!

**Comment by sabesansathananthan** [comment]
it will review by @esau-morais wait. Esau could you please review it.

**Comment by esau-morais** [comment]
> it will review by @esau-morais wait. Esau could you please review it.

It looks all good. 

- [ ] Keeping in the localStorage
- [ ] Changing the `select` value

**Comment by erdemuslu** [comment]
Hi, @esau-morais I don't understand. The value has already been in localStorage.

**Comment by esau-morais** [comment]
> Hi, @esau-morais I don't understand. The value has already been in localStorage.

It's just a quick resume about the feature. 

_Note: It's all good_

**Review by esau-morais — APPROVED** [review]
Thank you for contribute adding i18n to the website! 

_Note: It looks all good_

**Comment by erdemuslu** [comment]
Hi @sabesansathananthan Can you merge?

**Review by sabesansathananthan — CHANGES_REQUESTED** [review]
The bug is still there.

Capture

**Comment by erdemuslu** [comment]
@sabesansathananthan Are you sure? I checked again now. It looks fine.

**Comment by erdemuslu** [comment]
Please can you check at the not private window? Because localStorage.setItem is not working at the private window.

**Review by sabesansathananthan — APPROVED** [review]
Thank you for your PR

**Pull request merged**
