### PR TITLE
Readme translation for Sinhala language added

### PR DESCRIPTION
**Pull request by bGuom**

### CODE REVIEW

**Comment by sabesansathananthan** [comment]
mchn, Could you please follow this instructions.

**Review by sabesansathananthan — APPROVED** [review]
Thank you for your PR

**Comment by bGuom** [comment]
@sabesansathananthan sure I am checking

**Comment by bGuom** [comment]
Thanks bro

**Review by sabesansathananthan — APPROVED** [review]

**Review by sabesansathananthan — APPROVED** [review]
Nice.. I will merge

**Comment by bGuom** [comment]
cool

**Pull request merged**
